"""
Shared infrastructure for propagating document-type classifier uncertainty
into the dossier_size_model per-document-type analyses (doc_type_three_groups,
doc_type_count_vs_presence). Those analyses used the TSV's per-type counts
as ground truth; those counts were themselves generated by the same
classifier with the same uneven per-type precision/recall corrected for in
scripts/dossier_composition/. This module joins the two datasets and reuses
the confusion matrix already fit there (same classifier, same test set --
no need to refit it).

Scope note: this only applies to per-document-TYPE outcomes. The aggregate
num_docs models (model_dossier_size*.py) use total segment counts, which are
insensitive to document-type misclassification (only to segmentation/
start-page errors, a different, uncorrected uncertainty source) -- they are
out of scope here.

Two correction modes, both operating on the SAME 1307-dossier subset used
throughout dossier_size_model (joined to the full predicted corpus by
matching each dossier's numeric identifier to its pdf_name suffix -- verified
as a clean 1-to-1 join, 1309/1309 dossiers, before relying on it):

  point -- fast, CPU-runnable (no GPU needed). Deconvolves each dossier's
           segment-level predictions into EXPECTED (fractional) per-type
           counts using the DOCUMENT-TYPE confusion matrix's POSTERIOR MEAN.
           Corrects the average type-confusion bias, but its credible
           intervals still understate true uncertainty -- it propagates the
           classifier's point estimate, not its own uncertainty. Fits a
           negative-binomial likelihood to non-integer "observed" counts,
           which PyMC accepts (the NB log-density is defined via gamma
           functions for non-integer inputs) but is a deliberate
           approximation -- flagged wherever this mode's results are used.
           Segmentation (start_page) is held at its predicted boundaries in
           this mode -- deconvolving "expected number of segments" the same
           way isn't a simple per-page reweighting (segment boundaries are
           structural, not a soft label), and the start_page classifier is
           reliable enough (84.4%/97.9% precision/recall) that this is a
           minor simplification for a mode that's explicitly the fast/
           approximate one. Only `mi` corrects segmentation.

  mi    -- rigorous, and the one that matters: corrects BOTH document-type
           confusion AND segmentation (start_page) uncertainty jointly.
           Reuses dossier_composition/imputation.py's
           sample_segments_for_draw (built and validated there first) --
           each draw resamples start_page per page from the 2-class
           confusion matrix, rebuilds segment boundaries from that, majority-
           votes and resamples type on the NEW segments -- rather than
           duplicating that resegmentation logic here. Refits the regression
           per imputation, pools posteriors across imputations -- proper
           multiple imputation, at GPU-scale imputation counts. See
           doc_type_three_groups_uncertainty.py's docstring for the GPU
           setup (not runnable at practical scale on CPU).

           mi-mode output filenames carry a `joint` tag (idata_mi_joint_...,
           not idata_mi_...) specifically so they can never collide with or
           be silently skipped in favor of checkpoints from the EARLIER
           type-only version of this pipeline (before segmentation
           correction existed) -- if you have old idata_mi_{period}_{k}.nc
           files from that version sitting in the output dir, they're now
           orphaned, not reused; delete them or rerun to get joint-corrected
           results, don't mix them into a `pool` alongside the new ones.
"""

import sys
from pathlib import Path

import arviz as az
import numpy as np
import pandas as pd

_HERE = Path(__file__).resolve().parent
_COMPOSITION_DIR = _HERE.parent / "dossier_composition"
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_COMPOSITION_DIR))

from common import ALL_TYPES, DEFAULT_PREDICTIONS_PATH, DEFAULT_TEST_PREDICTIONS_PATH, OTHER, map_type  # noqa: E402
from imputation import load_pages, pages_to_segments, sample_segments_for_draw  # noqa: E402
from imputation import load_start_page_confusion_posterior  # noqa: E402
from model_doc_types import DOC_TYPE_COLS  # noqa: E402
from model_dossier_size_three_groups import DATA_PATH as SIZE_DATA_PATH, load_three_group_data  # noqa: E402

CONFUSION_IDATA_PATH = "data/dossier_composition/idata_confusion_matrix.nc"
START_PAGE_CONFUSION_IDATA_PATH = "data/dossier_composition/idata_start_page_confusion_matrix.nc"
UNCERTAINTY_OUT_DIR = "data/dossier_size_model/uncertainty"
RNG_SEED = 42


def join_pages_to_size_model(predictions_path: str = DEFAULT_PREDICTIONS_PATH,
                               size_data_path: str = SIZE_DATA_PATH) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Returns (pages, dossier_meta). pages: full-corpus PAGE-level (not yet
    segmented) predictions restricted to the 1307 known-age dossiers -- the
    page level is what segmentation correction needs (sample_segments_for_
    draw resamples start_page per page and rebuilds segments from scratch);
    callers that only need the fixed predicted segmentation (point mode) can
    derive it via naive_segments_from_pages(pages) -- NOT
    pages_to_segments(pages, "predicted_segment_id") directly, see that
    function's docstring for why. dossier_meta: one row per dossier
    (pdf_name, travel_year, minor_lt16,
    preadult_16_17, adult_18plus, era), keyed for merging after count
    aggregation.
    """
    size_df = load_three_group_data(size_data_path)
    all_pages = load_pages(predictions_path)

    id_to_pdf: dict[str, list[str]] = {}
    for p in all_pages["pdf_name"].unique():
        ident = p.rsplit("-", 1)[-1]
        id_to_pdf.setdefault(ident, []).append(p)

    size_df = size_df.copy()
    size_df["identifier_str"] = size_df["identifier"].astype(str)
    matched = size_df["identifier_str"].map(lambda i: id_to_pdf.get(i, []))
    n_matches = matched.apply(len)
    bad = int((n_matches != 1).sum())
    assert bad == 0, f"{bad} dossiers failed to match uniquely to a pdf_name -- join is no longer clean, investigate"
    size_df["pdf_name"] = matched.apply(lambda lst: lst[0])

    dossier_meta = size_df[["pdf_name", "travel_year", "minor_lt16", "preadult_16_17", "adult_18plus", "era"]]
    pages = all_pages[all_pages["pdf_name"].isin(dossier_meta["pdf_name"])].copy()
    return pages, dossier_meta


def join_pages_to_aggregate_data(predictions_path: str = DEFAULT_PREDICTIONS_PATH,
                                   size_data_path: str = SIZE_DATA_PATH) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Like join_pages_to_size_model, but dossier_meta additionally carries
    num_adults, num_minors, and the RAW (uncorrected) num_docs -- needed by
    aggregate_uncertainty.py to refit both the three-group model (uses
    minor_lt16/preadult_16_17/adult_18plus) and the temporal model (uses
    num_adults/num_minors, left as model_dossier_size_temporal.py defines
    them -- this correction is scoped to num_docs only, not to the separate
    two-group-vs-three-group adult-definition question) against the SAME
    corrected num_docs outcome. num_adults and num_docs are already native
    columns on the source TSV (load_three_group_data doesn't drop them, it
    only adds the three-group columns on top), so no merge with
    model_dossier_size.load_data is needed for those two -- only num_minors
    is derived (num_persons - num_adults, mirroring load_data exactly)."""
    size_df = load_three_group_data(size_data_path)
    size_df["num_minors"] = size_df["num_persons"] - size_df["num_adults"]
    all_pages = load_pages(predictions_path)

    id_to_pdf: dict[str, list[str]] = {}
    for p in all_pages["pdf_name"].unique():
        ident = p.rsplit("-", 1)[-1]
        id_to_pdf.setdefault(ident, []).append(p)

    size_df = size_df.copy()
    size_df["identifier_str"] = size_df["identifier"].astype(str)
    matched = size_df["identifier_str"].map(lambda i: id_to_pdf.get(i, []))
    n_matches = matched.apply(len)
    bad = int((n_matches != 1).sum())
    assert bad == 0, f"{bad} dossiers failed to match uniquely to a pdf_name -- join is no longer clean, investigate"
    size_df["pdf_name"] = matched.apply(lambda lst: lst[0])

    dossier_meta = size_df[[
        "pdf_name", "travel_year", "minor_lt16", "preadult_16_17", "adult_18plus", "era",
        "num_adults", "num_minors", "num_docs",
    ]]
    pages = all_pages[all_pages["pdf_name"].isin(dossier_meta["pdf_name"])].copy()
    return pages, dossier_meta


def load_test_prior(test_predictions_path: str = DEFAULT_TEST_PREDICTIONS_PATH) -> np.ndarray:
    test = pd.read_csv(test_predictions_path, sep="\t")
    test["true_mapped"] = test["document_type"].apply(map_type)
    counts = test["true_mapped"].value_counts().reindex(ALL_TYPES, fill_value=0).to_numpy()
    return (counts + 1.0) / (counts + 1.0).sum()


def point_correction_matrix(confusion_idata_path: str = CONFUSION_IDATA_PATH,
                              test_predictions_path: str = DEFAULT_TEST_PREDICTIONS_PATH) -> np.ndarray:
    """(n_pred, n_true) matrix: correction[j, i] = P(true=i | predicted=j),
    using the confusion matrix's POSTERIOR MEAN (not resampled -- the fast
    point-estimate path)."""
    idata = az.from_netcdf(confusion_idata_path)
    p_mean = idata.posterior["p"].mean(dim=("chain", "draw")).values  # (n_true, n_pred)
    prior = load_test_prior(test_predictions_path)
    unnorm = p_mean * prior[:, None]
    correction = unnorm / unnorm.sum(axis=0, keepdims=True)
    return correction.T  # (n_pred, n_true)


def select_posterior_draws(n_total_imputations: int, confusion_idata_path: str = CONFUSION_IDATA_PATH,
                             rng_seed: int = RNG_SEED) -> np.ndarray:
    """Deterministically picks n_total_imputations distinct posterior draws
    of the confusion matrix -- draw k is always the same regardless of how
    the work is later sharded, so `--shard a/M` and `--shard b/M` never
    overlap no matter which runs first or on which machine."""
    idata = az.from_netcdf(confusion_idata_path)
    p = idata.posterior["p"].stack(sample=("chain", "draw")).transpose("sample", "true_type", "pred_type")
    p_all = p.values
    rng = np.random.default_rng(rng_seed)
    idx = rng.choice(p_all.shape[0], size=n_total_imputations, replace=False)
    return p_all[idx]


def soft_expected_counts(segments: pd.DataFrame, correction: np.ndarray) -> pd.DataFrame:
    """Point-corrected (fractional) per-dossier per-type expected counts."""
    type_idx = segments["type_idx"].to_numpy()
    weights = correction[type_idx]  # (n_segments, n_types)
    weight_df = pd.DataFrame(weights, columns=ALL_TYPES, index=segments.index)
    combined = pd.concat([segments[["pdf_name"]], weight_df], axis=1)
    return combined.groupby("pdf_name").sum()


def load_start_page_posterior(n_total_imputations: int,
                                start_page_confusion_idata_path: str = START_PAGE_CONFUSION_IDATA_PATH,
                                test_predictions_path: str = DEFAULT_TEST_PREDICTIONS_PATH,
                                rng_seed: int = RNG_SEED) -> tuple[np.ndarray, np.ndarray]:
    """Thin wrapper around dossier_composition.imputation.
    load_start_page_confusion_posterior with the same n_draws contract as
    select_posterior_draws (deterministic draw selection, so shard a/M and
    b/M never overlap) -- kept separate from select_posterior_draws since
    that one is hardcoded to the document-type confusion matrix's variable
    names ("true_type"/"pred_type" vs. start_page's "true_label"/"pred_label")."""
    return load_start_page_confusion_posterior(
        start_page_confusion_idata_path, test_predictions_path, n_draws=n_total_imputations
    )


def point_correction_start_page(start_page_confusion_idata_path: str = START_PAGE_CONFUSION_IDATA_PATH,
                                  test_predictions_path: str = DEFAULT_TEST_PREDICTIONS_PATH) -> np.ndarray:
    """(2,) array: correction[j] = P(true start_page='yes' | predicted=j),
    j in [no, yes] order, using the start-page confusion matrix's POSTERIOR
    MEAN -- the point-estimate analog of point_correction_matrix above, but
    for the 2-class start_page classifier. Used to correct AGGREGATE
    num_docs (see aggregate_uncertainty.py): unlike the per-document-type
    analyses, a dossier's total document count depends only on where
    segments START, not on what TYPE each segment is predicted as, so the
    document-type confusion matrix is irrelevant here and only this
    correction is needed."""
    idata = az.from_netcdf(start_page_confusion_idata_path)
    p_mean = idata.posterior["p"].mean(dim=("chain", "draw")).values  # (true_label, pred_label), order [no, yes]
    test = pd.read_csv(test_predictions_path, sep="\t")
    counts = test["start_page"].value_counts().reindex(["no", "yes"], fill_value=0).to_numpy()
    prior = (counts + 1.0) / (counts + 1.0).sum()
    unnorm = p_mean * prior[:, None]
    correction = unnorm / unnorm.sum(axis=0, keepdims=True)  # columns: P(true=i | pred=j)
    return correction[1, :]  # P(true='yes' | pred=j), j=[no,yes]


def expected_num_docs_point(pages: pd.DataFrame, correction_yes: np.ndarray) -> pd.Series:
    """Point-corrected (fractional) EXPECTED num_docs per dossier: each
    page's hard predicted_start_page label is replaced by its posterior-
    mean-corrected P(true start='yes'), summed per dossier. The first page
    of every dossier is forced to contribute 1.0 regardless of its own
    correction -- a dossier can't have zero documents, the same structural
    assumption reconstruct_segments_from_start encodes for the hard-
    imputation (mi-mode) path in dossier_composition/imputation.py. Returns
    a pdf_name-indexed Series, same shape/contract soft_expected_counts has
    for per-type counts."""
    pred_idx = (pages["predicted_start_page"] == "yes").astype(int).to_numpy()
    p_start = correction_yes[pred_idx]
    pdf_name = pages["pdf_name"].to_numpy()
    is_first = np.empty(len(pdf_name), dtype=bool)
    is_first[0] = True
    is_first[1:] = pdf_name[1:] != pdf_name[:-1]
    p_start = np.where(is_first, 1.0, p_start)
    return pd.Series(p_start, index=pages.index).groupby(pdf_name).sum()


def hard_imputed_counts_joint(pages: pd.DataFrame, type_p_draw: np.ndarray, type_prior: np.ndarray,
                                start_p_draw: np.ndarray, start_prior: np.ndarray,
                                rng: np.random.Generator) -> pd.DataFrame:
    """One JOINT (segmentation + type) multiple-imputation draw's per-dossier
    per-type integer counts. Reuses dossier_composition/imputation.py's
    sample_segments_for_draw for the actual resegmentation + type resampling
    (validated there against synthetic cases and cross-checked on real data
    before being trusted) -- this function only does the final aggregation
    to a pdf_name x type count table, matching the shape/contract the
    (now-removed) type-only hard_imputed_counts had, so to_long_format and
    everything downstream is unchanged.
    """
    segments = sample_segments_for_draw(pages, type_p_draw, type_prior, start_p_draw, start_prior, rng)
    onehot = pd.DataFrame(
        np.eye(len(ALL_TYPES), dtype=int)[segments["type_idx"].to_numpy()], columns=ALL_TYPES, index=segments.index
    )
    combined = pd.concat([segments[["pdf_name"]], onehot], axis=1)
    return combined.groupby("pdf_name").sum()


def to_long_format(dossier_meta: pd.DataFrame, counts_wide: pd.DataFrame, round_counts: bool = False) -> pd.DataFrame:
    """counts_wide: pdf_name-indexed, columns include DOC_TYPE_COLS (+ Other,
    ignored here). Returns the long_df shape model_doc_types_three_groups.
    build_model / model_doc_types_count_vs_presence.build_model expect."""
    wide = counts_wide[DOC_TYPE_COLS].reset_index()
    if round_counts:
        wide[DOC_TYPE_COLS] = wide[DOC_TYPE_COLS].round().astype(int)
    wide = wide.merge(dossier_meta, on="pdf_name")
    long_df = wide.melt(
        id_vars=["travel_year", "minor_lt16", "preadult_16_17", "adult_18plus", "era"],
        value_vars=DOC_TYPE_COLS, var_name="doc_type", value_name="doc_count",
    )
    return long_df.reset_index(drop=True)


def gpu_sample_kwargs(use_gpu: bool) -> dict:
    """kwargs for pm.sample(): numpyro/JAX on GPU if requested (needs
    `pip install numpyro "jax[cuda12]"` on the GPU box -- not available
    locally, see doc_type_three_groups_uncertainty.py's docstring), plain
    PyMC NUTS on CPU otherwise."""
    if not use_gpu:
        return {}
    return {"nuts_sampler": "numpyro", "nuts_sampler_kwargs": {"chain_method": "vectorized"}}
